version: '2'
services:
  #- install node deps first `docker-compose run agenda npm install`
  pyflask:
    build: .
    command: python main.py
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/src/app
    environment:
      - HTTP_AUTH_MODE=basic
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
