version: '2'
services:
  #- install node deps first `docker-compose run agenda npm install`
  agenda:
    build: .
    command: make run
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/src/app
    environment:
      - MONGODB_HOST=agenda-mongo
      - HTTP_AUTH_MODE=basic
      - AUTH_USER_NAME=${AUTH_USER_NAME}
      - AUTH_PASSWORD=${AUTH_PASSWORD}